// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFr-M1MG4nvzHS-70btN9Q4DD0KogTHY',
    appId: '1:205110129715:web:b4fe8fde447aa7ce761f46',
    messagingSenderId: '205110129715',
    projectId: 'captain-drive-webbing',
    authDomain: 'captain-drive-webbing.firebaseapp.com',
    storageBucket: 'captain-drive-webbing.firebasestorage.app',
    measurementId: 'G-TVWZWP7BG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbEa037QoGupp-qhkEKCOtSj_b4ySiLdQ',
    appId: '1:205110129715:android:f946e58f0a4efa4f761f46',
    messagingSenderId: '205110129715',
    projectId: 'captain-drive-webbing',
    storageBucket: 'captain-drive-webbing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwvqzaKmR456PtCNNh7HyHZxitMFKmeDc',
    appId: '1:205110129715:ios:7545a10f7cf27b8e761f46',
    messagingSenderId: '205110129715',
    projectId: 'captain-drive-webbing',
    storageBucket: 'captain-drive-webbing.firebasestorage.app',
    iosBundleId: 'com.example.captainDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ny9wYHIo1gLmYH-1Zkg_Gf-06gpm2dI',
    appId: '1:362036690379:ios:311d417838010f0d7f0a4e',
    messagingSenderId: '362036690379',
    projectId: 'captain-drive-77080',
    storageBucket: 'captain-drive-77080.appspot.com',
    androidClientId:
        '362036690379-d5gdsb07tplpv0evm1mlk00bnj82794b.apps.googleusercontent.com',
    iosClientId:
        '362036690379-fpljsjh1l8rsgdtbqeu8cvg4e27sndnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.captainDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbu6Uq0hw9CHOvABb4YaGNcxBH0olBsog',
    appId: '1:362036690379:web:e17917779f5679e87f0a4e',
    messagingSenderId: '362036690379',
    projectId: 'captain-drive-77080',
    authDomain: 'captain-drive-77080.firebaseapp.com',
    storageBucket: 'captain-drive-77080.appspot.com',
    measurementId: 'G-RNBDLHPLEK',
  );
}